// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEs1m6RpArPYckcb4P0nDVYj_EREL88mU',
    appId: '1:240678081601:android:0c9c2aa3eb5b14640fe2c0',
    messagingSenderId: '240678081601',
    projectId: 'musical-director',
    storageBucket: 'musical-director.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5YlZsBu_0UMIxlM7AmvDRpsfCFYdNxN8',
    appId: '1:240678081601:ios:90986172bb9108260fe2c0',
    messagingSenderId: '240678081601',
    projectId: 'musical-director',
    storageBucket: 'musical-director.firebasestorage.app',
    androidClientId: '240678081601-g7hplv99nq4c74fkfkmshti92lbdfamc.apps.googleusercontent.com',
    iosClientId: '240678081601-kd18er3dlh356ri874aupvfqdm54esv9.apps.googleusercontent.com',
    iosBundleId: 'com.example.directorMusicalApp',
  );
}
